name: Deploy Action
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm install
      - name: Set Registry Config
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> $HOME/.npmrc
          npm config set @nestcoinco:registry https://npm.pkg.github.com/nestcoinco
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          npm run lint && npm run build
          npm publish
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
